In [125]:
import json
import pandas as pd

In [126]:
CPI_Index = pd.read_csv("data/รหัสหมวดดัชนี CPI_INDEX 31-8-2020.csv")
# pd.read_csv('../data/รหัสหมวดดัชนี CPI_INDEX 31-8-2020.csv')
CPI_index_id = CPI_Index['รหัสดัชนี'][1:]
CPI_index_id_list = CPI_index_id.tolist()
# CPI_index_id_list

In [127]:
#แหล่งข้อมูล: https://data.moc.go.th/OpenData/CPIGIndexes
data = []

def addData(lists):
    for i in range(len(lists)):
        data.append(lists[i])

In [117]:
region_id = "1" #ภาคกลาง
from_year="2017"
to_year="2019"

# url = 'https://dataapi.moc.go.th/cpig-indexes?region_id=1&index_id=1000000000000000&from_year=2017&to_year=2019'

for i in CPI_index_id_list:
    url = "https://dataapi.moc.go.th/cpig-indexes?region_id=" + region_id + "&index_id=" + str(int(i)) + "&from_year=" + from_year + "&to_year=" + to_year
    response = urllib.request.urlopen(url)
    raw_json = response.read().decode("utf-8")
    addData(json.loads(raw_json))
print(len(data))

6232

In [124]:
df = pd.json_normalize(data)
df

,index_id,index_description,region_id,region_name,base_year,year,month,price_index,mon,yoy,aoa
0,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,1,101.53,0.40,1.61,1.61
1,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,2,101.51,-0.02,1.24,1.42
2,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,3,100.80,-0.70,0.84,1.23
3,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,4,101.05,0.25,-0.38,0.82
4,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,5,101.64,0.58,-1.48,0.36
...,...,...,...,...,...,...,...,...,...,...,...
6227,9520000000000000,"CPI ไม่รวมน้ำมัน 91 , 95 , ดีเซล",1,ภาคกลาง,2015,2019,12,102.32,-0.11,0.40,0.58
6228,9700000000000000,CPI ไม่รวมอาหารสด,1,ภาคกลาง,2015,2019,11,102.31,0.08,-0.58,-0.24
6229,9700000000000000,CPI ไม่รวมอาหารสด,1,ภาคกลาง,2015,2019,12,102.38,0.07,0.21,-0.21
6230,9800000000000000,CPI ไม่รวมพลังงาน,1,ภาคกลาง,2015,2019,11,102.96,-0.18,0.34,0.87
6231,9800000000000000,CPI ไม่รวมพลังงาน,1,ภาคกลาง,2015,2019,12,102.87,-0.09,0.44,0.83

In [129]:
df.isna().sum()

index_id             0
index_description    0
region_id            0
region_name          0
base_year            0
year                 0
month                0
price_index          0
mon                  0
yoy                  0
aoa                  0
dtype: int64

In [135]:
df['index_description'].drop_duplicates().to_list()

['หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์',
 'อาหารปรุงที่บ้าน',
 'ข้าว  แป้งและผลิตภัณฑ์จากแป้ง',
 'ข้าว',
 'แป้งและผลิตภัณฑ์จากแป้ง',
 'แป้ง',
 'ผลิตภัณฑ์จากแป้ง',
 'เนื้อสัตว์ เป็ดไก่ และสัตว์น้ำ',
 'เนื้อสัตว์',
 'เนื้อสัตว์สด',
 'เนื้อสัตว์แปรรูป',
 'เป็ด ไก่',
 'เป็ด ไก่  สด',
 'เป็ด ไก่  สำเร็จรูปและแปรรูป',
 'ปลาและสัตว์น้ำ',
 'ปลาน้ำจืดสด',
 'ปลาน้ำทะเลสด',
 'สัตว์น้ำ',
 'ปลาแปรรูป',
 'สัตว์น้ำแปรรูป',
 'ไข่และผลิตภัณฑ์นม',
 'ไข่',
 'นมและผลิตภัณฑ์นม',
 'ผักและผลไม้',
 'ผักสดแปรรูปและอื่นๆ',
 'ผักสด',
 'ผักแปรรูปและอื่นๆ',
 'ผลไม้สดแปรรูปและอื่นๆ',
 'ผลไม้สด',
 'ผลไม้แปรรูปและอื่น ๆ',
 'เครื่องประกอบอาหาร',
 'ผลิตภัณฑ์น้ำตาล',
 'น้ำตาลและขนมหวาน',
 'เครื่องปรุงอาหาร',
 'น้ำมันและไขมัน',
 'เครื่องปรุงรส',
 'เครื่องดื่มไม่มีแอลกอฮอล์',
 'อาหารสำเร็จรูป',
 'อาหารบริโภค-ในบ้าน',
 'อาหารบริโภค-นอกบ้าน',
 'หมวดเครื่องนุ่งห่มและรองเท้า',
 'ผ้าและเสื้อผ้า',
 'บุรุษ',
 'เครื่องแบบชาย',
 'เสื้อบุรุษ',
 'กางเกงบุรุษ',
 'เสื้อผ้าบุรุษอื่นๆ',
 'เครื่องประดับบุรุษ',
 'สตรี',
 'เครื่องแบบหญิง',
 'เสื้อสตรี',
 'กางเกงสตรีและกระโปรงสตรี',
 'เสื้อผ้าสตรีอื่นๆ',
 'เด็ก',
 'เครื่องแบบเด็ก',
 'เสื้อเด็ก',
 'กางเกงเด็ก',
 'เสื้อผ้าเด็กอื่นๆ',
 'ค่าจ้างตัดเย็บและอุปกรณ์',
 'ค่าจ้าง',
 'ผลิตภัณฑ์รองเท้า',
 'รองเท้าบุรุษ',
 'รองเท้าหุ้มส้นบุรุษ',
 'รองเท้ากีฬาและผ้าใบบุรุษ',
 'รองเท้าแตะบุรุษ',
 'รองเท้าสตรี',
 'รองเท้าหุ้มส้นสตรี',
 'รองเท้ากีฬาและผ้าใบสตรี',
 'รองเท้าแตะสตรี',
 'รองเท้าเด็ก',
 'รองเท้ากีฬาและผ้าใบเด็ก',
 'รองเท้าแตะเด็ก',
 'ค่าซ่อมแซมและดูแลรักษา',
 'ค่าซ่อมแซม',
 'หมวดเคหสถาน',
 'ค่าที่พักอาศัย',
 'ค่าเช่า',
 'วัสดุก่อสร้าง',
 'เครื่องสุขภัณฑ์',
 'ค่าแรง',
 'อุปกรณ์ซ่อมแซมบ้าน',
 'ไฟฟ้า  เชื้อเพลิง  น้ำประปาและแสงสว่าง',
 'ไฟฟ้า',
 'เชื้อเพลิงในบ้าน',
 'น้ำประปา',
 'แสงสว่าง',
 'สิ่งทอสำหรับใช้ในบ้าน',
 'เครื่องใช้เบ็ดเตล็ดในบ้าน',
 'เครื่องแต่งบ้านและบริภัณฑ์อื่นๆ',
 'เครื่องแต่งบ้าน',
 'บริภัณฑ์อื่น ๆ',
 'สิ่งที่เกี่ยวกับทำความสะอาด',
 'คนรับใช้ / คนงาน',
 'หมวดการตรวจรักษาและบริการส่วนบุคคล',
 'ค่าตรวจรักษาและค่ายา',
 'ค่ายาและเวชภัณฑ์',
 'ค่ายา',
 'เวชภัณฑ์',
 'ค่ารักษาพยาบาล',
 'คนไข้นอก',
 'ค่าตรวจโรครักษา ค่าบริการ และค่ายาของคนไข้นอก',
 'ค่าทำฟัน',
 'ค่าบริการด้านรังสี',
 'ค่าบริการอื่น ๆ',
 'ค่าตรวจวินิจฉัยทางห้องปฏิบัติการ',
 'คนไข้ใน',
 'ค่าตรวจรักษา ค่าบริการ และค่ายาของคนไข้ใน',
 'ค่าใช้จ่ายส่วนบุคคล',
 'ค่าของใช้ส่วนบุคคล',
 'ค่าบริการส่วนบุคคล',
 'ค่าบริการส่วนบุคคลเพื่อความสวยงาม',
 'ค่าบริการส่วนบุคคลเพื่อความผ่านคลาย',
 'ค่าบัตรประกันสุขภาพและประกันชีวิต',
 'หมวดพาหนะ การขนส่ง และการสื่อสาร',
 'ค่าโดยสารสาธารณะ',
 'ค่าโดยสารในท้องถิ่น',
 'ค่าโดยสารนอกท้องถิ่น',
 'ยานพาหนะและน้ำมันเชื้อเพลิง',
 'ค่าซื้อยานพาหนะ',
 'ยานพาหนะ',
 'อุปกรณ์ยานพาหนะ',
 'น้ำมันเชื้อเพลิง',
 'ค่าบริการบำรุงรักษายานยนต์',
 'ค่าภาษีและประกันภัยรถยนต์',
 'ค่าภาษี',
 'ค่าประกันภัยรถ',
 'การสื่อสาร',
 'ค่าบริการการสื่อสาร',
 'เครื่องรับอุปกรณ์สื่อสาร',
 'หมวดการบันเทิงการอ่าน การศึกษา และการศาสนา',
 'การบันเทิงและการอ่าน',
 'ค่าธรรมเนียมและค่าสมาชิก',
 'ค่าอุปกรณ์กีฬาและเครื่องเล่น',
 'อุปกรณ์กีฬา',
 'ของเล่น',
 'ค่าการบันเทิง',
 'ค่าใช้จ่ายเกี่ยวกับสัตว์เลี้ยง',
 'ค่าใช้จ่ายเกี่ยวกับการทำสวนประดับบ้าน',
 'ค่าอุปกรณ์การบันเทิง',
 'ค่าใช้จ่ายเกี่ยวกับการอ่าน',
 'ค่าใช้จ่ายในการเดินทางโอกาสพิเศษและท่องเที่ยว',
 'การศึกษา',
 'ค่าเล่าเรียนและค่าธรรมเนียมการศึกษา',
 'การศึกษาระดับประถมศึกษา',
 'การศึกษาระดับมัธยมศึกษาสายสามัญ',
 'การศึกษาระดับมัธยมศึกษา ด้านเทคนิคและอาชีวะ',
 'การศึกษาระดับอุดมศึกษา',
 'ค่าเรียนพิเศษ',
 'หนังสือและอุปกรณ์การศึกษา',
 'หนังสือ',
 'หนังสือแบบเรียนเอกชน',
 'อุปกรณ์เกี่ยวกับการศึกษา',
 'ค่าใช้จ่ายอื่น ๆ เกี่ยวกับการศึกษา',
 'การศาสนา',
 'ค่าอาหาร ของถวายพระ ไหว้เจ้าและอื่น ๆ',
 'เครื่องถวายพระ',
 'หมวดยาสูบและเครื่องดื่มมีแอลกอฮอล์',
 'ผลิตภัณฑ์ยาสูบ',
 'เครื่องดื่มมีแอลกอฮอลล์',
 'ผลิตภัณฑ์เบียร์',
 'ผลิตภัณฑ์ไวน์',
 'ผลิตภัณฑ์สุรา',
 'หมวดอื่น ๆ ไม่ใช่อาหาร และเครื่องดื่ม',
 'ไม่รวมอาหาร เครื่องดื่ม และพลังงาน',
 'อาหารและเครื่องดื่ม (ไม่รวมอาหารสด)',
 'กลุ่มอาหารสดและพลังงาน',
 'อาหารสด',
 'พลังงาน',
 'ดัชนีราคาผู้บริโภคพื้นฐาน',
 'ดัชนีราคาผู้บริโภคพื้นฐาน (ไม่รวมค่าเช่าบ้าน)',
 'น้ำมัน 91 , 95 , ดีเซล',
 'CPI ไม่รวมน้ำมัน 91 , 95 , ดีเซล',
 'CPI ไม่รวมอาหารสด',
 'CPI ไม่รวมพลังงาน']

In [134]:
df

,index_id,index_description,region_id,region_name,base_year,year,month,price_index,mon,yoy,aoa
0,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,1,101.53,0.40,1.61,1.61
1,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,2,101.51,-0.02,1.24,1.42
2,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,3,100.80,-0.70,0.84,1.23
3,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,4,101.05,0.25,-0.38,0.82
4,1000000000000000,หมวดอาหารและเครื่องดื่มไม่มีแอลกอฮอล์,1,ภาคกลาง,2015,2017,5,101.64,0.58,-1.48,0.36
...,...,...,...,...,...,...,...,...,...,...,...
6227,9520000000000000,"CPI ไม่รวมน้ำมัน 91 , 95 , ดีเซล",1,ภาคกลาง,2015,2019,12,102.32,-0.11,0.40,0.58
6228,9700000000000000,CPI ไม่รวมอาหารสด,1,ภาคกลาง,2015,2019,11,102.31,0.08,-0.58,-0.24
6229,9700000000000000,CPI ไม่รวมอาหารสด,1,ภาคกลาง,2015,2019,12,102.38,0.07,0.21,-0.21
6230,9800000000000000,CPI ไม่รวมพลังงาน,1,ภาคกลาง,2015,2019,11,102.96,-0.18,0.34,0.87
6231,9800000000000000,CPI ไม่รวมพลังงาน,1,ภาคกลาง,2015,2019,12,102.87,-0.09,0.44,0.83